### ISSUE TITLE
Admin Client NoSuchMethod Exception in Tomcat

### ISSUE THREAD

**Issue by hakuseki** [codecentric/spring-boot-admin#1719]
After upgrade to 2.4.1 I receive this Exception now in tomcat 9 and it keeps on coming in the logs periodically:

```
2021-05-04 05:35:01,412 [registrationTask1] o.s.s.s.TaskUtils$LoggingErrorHandler ERROR - Unexpected error occurred in scheduled task(95)
java.lang.NoSuchMethodError: org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getBasePath()Ljava/lang/String;
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementContextPath(ServletApplicationFactory.java:86)
	at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementBaseUrl(ServletApplicationFactory.java:77)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:154)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:80)
	at de.codecentric.boot.admin.client.registration.DefaultApplicationRegistrator.register(DefaultApplicationRegistrator.java:56)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

My config has not changed:

```
spring.boot.admin.client.url                                 = http://localhost:8080/adminServer
spring.boot.admin.client.username                            = username
spring.boot.admin.client.password                            = password
spring.boot.admin.client.instance.service-base-url           = http://localhost:8080

```

Several applications using 2.4.1 but runs on Spring Boot 2.2.0 and some on >2.3.4

**Comment by hakuseki** [comment]
Same for Tomcat 8.5

**Comment by SteKoe** [comment]
Hi @hakuseki,

we have tried to reproduce the issue but weren't able to find a constellation that matches the error your reported. Could you please provide an example repository that reproduces your issue? We'd then check how to fix it. 

TIA!

**Comment by hakuseki** [comment]
If I could I would but I can't really see where the problem is. 
We've had SBA for a while now and I try to upgrade our dependencies whenever there's a newer version of SBA and that was done for the latest release.

We have upgraded both the client application and our server application.
When testing locally we use Spring internal Tomcat container and then everything works fine but as soon as we deploy to a Tomcat server we receive these exceptions. 

Sorry if I can't provide more info.

**Comment by hakuseki** [comment]
Browsing thru the source and one thing stands out but I have no clue if it is significant.
You base the spring boot dependency on a later versaion than I do in my project.
Could that have any impact?
I mean the Exception is quite clear, ```NoSuchMethodError``` calling ```org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties```…

**Comment by hakuseki** [comment]
and I can confirm that by reverting to 2.3.1 it's working fine

**Comment by erikpetzold** [comment]
Hi @hakuseki 

the Spring Boot Admin Client 2.4 is calling `ManagementServerProperties.getBasePath()` which has been introduced in Spring Boot 2.4 (in older versions it was `getServlet().getContextPath()` which is deprecated now and will be removed in the next release)

So if your application is using Spring Boot 2.3, you also have to use SBA Client 2.3.
