### ISSUE TITLE
java.lang.NoClassDefFoundError: reactor/core/publisher/Sinks after upgrading to Spring Boot Admin 2.4.0 on Spring Boot 2.3.8.RELEASE

### ISSUE THREAD

**Issue by breun** [codecentric/spring-boot-admin#1642]
I have a project on Spring Boot 2.3.8.RELEASE that works ok with Spring Boot Admin 2.3.1.

When I upgrade Spring Boot Admin to version 2.4.0, I get this error:

```
2021-02-22 10:50:22.799  WARN [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'endpointDetector' defined in com.bol.axexss.order.SpringBootAdminApplication: Unsatisfied dependency expressed through method 'endpointDetector' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceRepository' defined in class path resource [de/codecentric/boot/admin/server/config/AdminServerAutoConfiguration.class]: Unsatisfied dependency expressed through method 'instanceRepository' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventStore' defined in class path resource [de/codecentric/boot/admin/server/config/AdminServerAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.codecentric.boot.admin.server.eventstore.InMemoryEventStore]: Factory method 'eventStore' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/core/publisher/Sinks
```

It seems the reason for this is that `de.codecentric.boot.admin.server.eventstore.InstanceEventPublisher` imports `reactor.core.publisher.Sinks`, but this class does not exist in the version 3.3.13.RELEASE of `reactor-core` as used by Spring Boot 2.3.8.RELEASE. It seems `reactor.core.publisher.Sinks` was introduced in `reactor-core` 3.4.0.

**Comment by joshiste** [comment]
please use spring boot 2.4.x for sba 2.4.x

**Comment by breun** [comment]
Due to company deployment reasons I depend on a framework that is based on Spring Boot 2.3.x (it will be upgraded to 2.4.x soon though), so I guess this means I can't use Spring Boot Admin 2.4.0 yet. (Spring Boot 2.2.x and 2.3.x are still supported by the Spring Boot team at the moment.) Is Spring Boot Admin compatibility with Spring Boot versions documented anywhere?

**Comment by marcellodesales** [comment]
> Due to company deployment reasons I depend on a framework that is based on Spring Boot 2.3.x (it will be upgraded to 2.4.x soon though), so I guess this means I can't use Spring Boot Admin 2.4.0 yet. (Spring Boot 2.2.x and 2.3.x are still supported by the Spring Boot team at the moment.) Is Spring Boot Admin compatibility with Spring Boot versions documented anywhere?

@breun Could you find any workaround for it? We are still in `2.3.x` as well...

**Comment by breun** [comment]
@marcellodesales No, we have upgraded to Spring Boot 2.4.x, and will soon upgrade to 2.5.x. Spring stopped supporting Spring Boot 2.3.x back in May.

**Comment by erikpetzold** [comment]
@marcellodesales for your application with Spring Boot 2.3.x you have to use SBA 2.3.x (client) -> Major and Minor should always match

You can however upgrade SBA Server, which can talk to older client versions

**Comment by marcellodesales** [comment]
@breun I just did the same thing... I just had to re-write an entire app from scratch using SpringBoot 2.5.4... Everything is working as expected now... 

@erikpetzold I tried to match it but the UI had errors, I couldn't get authentication to work on that version... I did spend a good couple of hours since I sent that message and I think I'm on 5hrs working on the latest version without any hiccups...  Thank you for the suggestion...
